version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  dialect = "typescript"
  style_guide = "standard"
  module_system = "es-modules"
  
[[analyzers]]
name = "test-coverage"
enabled = true

[analyzers.meta]
coverage_format = "lcov"
path = "coverage/lcov.info"

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[exclude]
paths = [
  "dist/**",
  "coverage/**",
  "node_modules/**",
  "**/*.spec.ts",
  "**/*.test.ts",
  "**/*.e2e-spec.ts"
]
