apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-store-api
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api-test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: online-store-api
            port:
              number: 80
