apiVersion: v1
kind: Service
metadata:
  name: online-store-api
  namespace: test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: online-store-api
